### ISSUE TITLE
Processing JPEGs with unusual extensions results in messed up colors

### ISSUE THREAD

**Issue by DoomTay** [jimp-dev/jimp#243]
With something as simple as this

```
var Jimp = require("jimp");

Jimp.read("http://web.archive.org/web/20001018040146/http://www.p2kthemovie.com/game/borgs/domains/Moltrsland.emb",function(err,image)
{
	if(err) console.error(err);
	else
	{
		image.write("processed.jpg");
	}
});
```

yellows and oranges will come out greens, and sky colors will come out purple.

It seems the core problem is that because of the unusual file extension, Jimp doesn't realize it's dealing with a JPEG and so fill in the YCbCr values as if it was using the RGB color space.

I could compensate for that with a transformation like this

```
image.scan(0, 0, image.bitmap.width, image.bitmap.height, function (x, y, i) {
	var r = this.bitmap.data[i + 0];
	var g = this.bitmap.data[i + 1];
	var b = this.bitmap.data[i + 2];
	
	if(image._originalMime == "image/jpeg")
	{
		this.bitmap.data[i + 0] = (0.299 * r) + (0.587 * g) + (0.114 * b);
		this.bitmap.data[i + 1] = 128 - (0.168736 * r) - (0.331264 * g) + (0.5 * b);
		this.bitmap.data[i + 2] = 128 + (0.5 * r) - (0.418688 * g) - (0.081312 * b);
	}
})
```

though the end result is a bit muddled.

This depends on https://github.com/eugeneware/jpeg-js/issues/23

**Comment by NoPinky** [comment]
I tried your code and, yes, it produces an image with a color shift of sort. But I don't think it is because of the wrong file extension, because:
- when your theory was right, then downloading the imagefile via browser and saving it on the harddisk with the right extension (jpg) and feed the script with this, it would result in a corrent picture without color shift. I tried that, but no, the result is still color shifted.
- then I tried to read another image (jpg) with the right extension and look at the processed.jpg your script produced: everything is fine, colors are right. Then I changed the extenstion from .jpg to .emb and tried the script again: the result is still fine, no color shift.

So I don't think that the file extension has anything todo with it. I suspect the file you have has some exotic implementation of the jpg standard that a image viewer (tried with IrfanView on Windows 10 and Eye of MATE on Ubuntu MATE) and a browser can display it correctly but jimp can't.

I got currious and installed ImageMagick on Ubuntu to use the 'identify -verbose' command to see if there is anything wrong with that file. But it seems like everything is in order. I did the same with the cat.jpg file and diffed the 2 outputs, apart from the differences resulting from the different resolution and color channel statistics (because they are different images with different sizes and contents) there is only one difference: your image (Moltrsland.emb) has Iterlace: JPEG instead of Interlace: None (in the cat.jpg). Maybe this is the culpit, maybe not...

That's all I can contribute to help the ones who know how to fix this. I don't know about the low level details how to read JPGs.
