### ISSUE TITLE
Bundle Size is hUUUUUge

### ISSUE THREAD

**Issue by hipstersmoothie** [jimp-dev/jimp#493]
Our code: 143.84kb uncompressed, 16.14kb gzipped
All code: 1.43mb uncompressed, 158.21kb gzipped

😮 

https://bundlephobia.com/scan-results?packages=bignumber.js@7.2.1,bmp-js@0.1.0,buffer@5.0.2,exif-parser@0.1.9,file-type@8.1.0,jpeg-js@0.3.4,load-bmfont@1.2.3,mime@2.3.1,mkdirp@0.5.1,omggif@1.0.9,phin@2.9.0,pixelmatch@4.0.0,pngjs@3.0.0,tinycolor2@1.1.2,utif@2.0.0

```js
import Jimp from 'jimp/es'

Jimp.read('./exampleImages/npm.jpg').then(image => {
  image.resize(10, Jimp.AUTO).getBuffer(Jimp.AUTO, (err, res) => {
    console.log(res)
  })
})
```

<img width="1411" alt="screen shot 2018-07-28 at 10 54 38 pm" src="https://user-images.githubusercontent.com/1192452/43363421-4d8df60c-92b9-11e8-8bb8-27a1b7659a5e.png">

Offenders (only using stat sizes unless otherwise specified, cause parse time matters!):

* utif - TIFF support
	* total (including deps): 441.35kB 😭 119kB minified
	* size: 38kb
	* requires:
		* jpgjs = 190.02kB
		* pako = 213.33kB
	* potential replacements:
		* tiff@3.0.0 - 19.6kB minified
		* decode-tiff@0.2.1 - 3.8kB minified
		* both these have no encoder so we'd have to figure that out

* bignumber.js - used for hashes #497 
	* size:  84.19kB with tree-shaking 79.41kB, minified 17.7kB
	* potential replacements:
		* big.js - 5.9kB minified
		* buffer? maybe we don't even need the dep
		* @babel/plugin-syntax-bigint - this would be really cool. IDK how big it would be. the packaged minified is only 1.7kB though
			* https://developers.google.com/web/updates/2018/05/bigint

Image:

We use a bunch of different libraries to process images. Switching to a library that does multiple could provide a big win. Options

* images@3.0.1 - processes png, jpeg, and gif 9.8kB minified

* pngjs - encode/decode
	* potential replacements:
		* yapd@1.0.0 - 8.6kB minfified - low downloads though

Lower Hanging Fruit:

* exif-parser - load exif data from JPEG image
	* size: 20.7kB minified
	* potential replacements:
		* jpeg-exif@1.1.2 - 5.6kB minified
		* ~exif-js@2.3.0 - 14.5kB also supports TIFF!~ doesn't support node runtime!?
		* exif-reader@1.0.2 - 12kB

* mime #496
	* size: 32.3kB minified
	* mime/lite = 8.21kB
	* potential replacements:
		* file-mime@0.0.13 - 4.7kB minified
			* probably supports less formats, but we really only need 5 anyway (gif, tiff, png, jpeg, bmp)
		* Just write our own. We only need to identify the above 5

**Comment by hipstersmoothie** [comment]
I'm gonna switch `exif-parser` to `jpeg-exif` once my two PRs are merged. 

https://github.com/zhso/jpeg-exif/pull/9 - So we don't have to read the file twice
https://github.com/zhso/jpeg-exif/pull/10 - So we can support tiff as well.

The only information from exif that we use is the orientation. `jpeg-exif` exposes that property so we can easily switch to it! 15kB of the bundle but that's still one less cut 😜

**Comment by peter-mouland** [comment]
great bit of analysis - i'll have to do the same on my projects!

**Comment by hipstersmoothie** [comment]
Bundlephobia is a great tool! With that plus webpack-bundle-analyze you can really hunt down bloated dependancies.

**Comment by hipstersmoothie** [comment]
Opened #496 to switch to our own mime type lookup.

**Comment by hipstersmoothie** [comment]
Opened #497 switch from BigNumber.js to any-base

**Comment by Killian22** [comment]
Yesterday we started using jimp to rotate image created using node-canvas.  

Adding jimp added 2000~ files to the project and it seemed quite large.

The only thing being done is
`Jimp.read(canvas.toBuffer()).then(image => {
                    image.rotate(rotation);

                    image.getBuffer(Jimp.MIME_PNG, (err, buffer) => {`

Is there a lighter weight version of JIMP that supports just this? Or do you have any suggestions on how to rotate without diving into image processing code?

**Comment by haggins** [comment]
I'm currently researching which image library might fit best for my "server-less" web app. I just need scaling, resizing and filling background with a color. It would be really cool if features would be modularized so that only that code is included in ones project which you actually use.

Apart from that, this seems to be a very nice project!

**Comment by hipstersmoothie** [comment]
The problem with the bundle doesn't really come from the functions that jimp does. Rather it is the encoding and decoding of images that adds a lot to the bundle. If you were to take out all the rotate, resize, etc the bundle size would basically be the same because the image libraries are the majority of the bundle.

Does your web app require jimp to decode the images? If the answer is yes then then you won't really find a smaller pure JS image processing library.

**Comment by hipstersmoothie** [comment]
@Killian22 the same goes for you. decoding images is hard and takes some code to do. The getbuffer function uses libraries fro png, jpg, bmp, and tiff. those libararies account for the brunt of jimp. 

I've wrestled with this fact for the past week. In the future I may come up with a way to only include the decoding libraries that are needed but until then I think the best solution is to lazy load jimp or load it in a webworker. Since jimp really shouldn't be needed on page load you should be able to do this.

In my mind the two places you would use jimp in a frontend project would be:

* during the build step to transform images somehow
* after the page loads and a user wants to do something with an image

I good way to do this would be with code-splitting in webpack with `import()` and possibly in combination with `prefetch` or `preload` so the library is already loaded once the user gets to it.

I've also been thinking of breaking off individual function into modules that just operate on buffers. But this would require a pretty big overhaul of the codebase and a major release. Speaking with @oliver-moran backwards compatibility is a big focus and a major breaking change isn't on the horizon. Right now I want to focus on error handling.

**Comment by Killian22** [comment]
Thanks! That is what I wanted to hear!  ( I think ) .  The 2k File check in just was kinda scary adding to the project haha.

We're not using this front-end. We have draw routines on the front end using canvas. And even though our app is C# Web app , we are using Node + IISNode + node-canvas so that we can use the same code frontend + backend.

Our backend images are used in reports and those images need rotated, but we don't want to update draw routines, so googling 'node image rotate' this came up first and I gave it a try!

Thanks for your activity!

**Comment by MikeKovarik** [comment]
@hipstersmoothie Hello, I'm author of [exifr](https://github.com/MikeKovarik/exifr) and I'd like to suggest it as the replacement for `exif-parser`. I have written exifr from the ground up for performance and modularity. In its full it supports many formats (jpeg, tiff, heic) and metadata types (tiff/exif, xmp, iptc, icc, jfif) each of which adds +3-10kb to the full bundle. But it's all modular so every feature and parser can be excluded. Even exif tag dictionaries (believe it or not but just dictionaries can take up to 40kb) can be avoided altogether driving the size of the library down to the 15kb core.

I know it's still a bit more than desired but I'd like to improve on that, make exifr even more modular, lighter and tailor it to your needs if you'd be interrested.

The 15kb consists of two things:

1) chunked reader - reads just a first few bytes of the image, saves a lot of memory and time, [enables to parse hundreds of photos without crashing the browser](https://raw.githubusercontent.com/MikeKovarik/exifr/master/logo/readme-gif.gif)
2) support for node.js and browser - there's a wrapper for `ArrayBuffer`, `Uint8Array` and node's `Buffer`

Since jimp works with the full image, the chunked reader is quite useless here and could be dropped altogether. This specifically is [already possible](https://github.com/MikeKovarik/exifr#advanced-apis) but there's more that could be done and like I said, I'd be happy to work with you (on both sides, improvements to exifr as well as PRs to jimp) if you would be interrested.

Thanks, Mike

**Comment by hipstersmoothie** [comment]
If it can get the bundle size down and is a better solution for exif parsing, I'm all for you integrating it into jimp! Feel free to make PRs as you see fit and I'll try to address them in a timely manner

**Comment by hipstersmoothie** [comment]
I'm gonna close this. Jimp included image encoder and decoders and those aren't small. If a use wants a smaller jimp the best way is to use jump custom to only include what you need
