### ISSUE TITLE
Fix new Jimp()

### ISSUE THREAD

**Issue by hipstersmoothie** [jimp-dev/jimp#503]
When creating a `new Jimp()` asyncronous stuff shouldn't happen.

```js
const image = new Jimp()
console.log(image);
// result is <Jimp pending> so user would have to use timeouts to guess when it is useable
```

it should be the folowing.

```js
const image = new Jimp()
console.log(image);
// result is <Jimp 400x300>
image.resize(10, Jimp.auto).greyscale();
```

To achieve this all we have to do is use `fs.readFileSync` rather than `fs.readFile` and stop supporting the callback. The callback within the constructor is an anti-pattern anyway.

This will be a breaking change. But it really cleans up the API.

related to #303

**Comment by hipstersmoothie** [comment]
Although we probably don't want to block on a sync readFile. it could be an option

```js
const image = new Jimp({ 
	sync: true
})
```

**Comment by jerryjappinen** [comment]
Just bumped into this. Wow, looks like an old issue.

In my use case, I might be conditionally either loading an external base image, or creating a new blank one. The difference with `Jimp.read()` and `new Jimp()` is a bit unintuitive, but what's worse is that you have to handle them differently in the code. I'm using async/await with `.read()`, but I having to support the callback pattern with `new Jimp()` forces me to structure the entire file in an entirely different way (which also conflicts with the rest of the codebase, since everything is async/await now).

You can work around this, it's not like it breaks everything, but it's annoying and completely unnecessary. I think the right solution is `Jimp.create()` or `await Jimp.create()`.

**Comment by hipstersmoothie** [comment]
Fixed in v1
