### ISSUE TITLE
.rgba(false) does not work

### ISSUE THREAD

**Issue by Jimbly** [jimp-dev/jimp#681]
# Expected Behavior

Expect to save the image without the alpha channel.

# Current Behavior

Getting an image byte-wise re-interpretted from RGBA to RGB.

# Failure Information (for bugs)

## Steps to Reproduce

```javascript
require('jimp').read('test.png', function (err, image) {
  image.rgba(false).write('out.png');
})
```

**Screenshots**
In (and expected out):
![rgba](https://user-images.githubusercontent.com/774383/50306891-56b95680-045c-11e9-936a-c9f81947fcf3.png)
Actual out:
![rgb](https://user-images.githubusercontent.com/774383/50306899-5faa2800-045c-11e9-8d34-45750123e484.png)

## Context

- Jimp Version: 0.6.0
- Operating System: Windows 10
- Node version: 8.11.3

**Comment by jeremypele** [comment]
Same issue here. Any updates?

**Comment by cppchriscpp** [comment]
To note, this happens if you use `.getBase64`  instead of `.write` as well.

**Comment by Axenu** [comment]
I think I have found the problem.

It appears that the encoder for PNG files are setting both output AND input alpha channel to `image.rgba()`. This results in the input being read as RGB instead of RGBA which destroys the output. 

The solution should be to change Jimp/packages/type-png/src/index.js:50 from
`inputHasAlpha: data._rgba`
to
`inputHasAlpha: data.bitmap.alpha`

I tried to fork it and make the change but one of the tests fail, and I am unable to figure out what the test even does. The important part for me is that the image ends up looking as I expect it to.

**Comment by panalgin** [comment]
Same happens when I try to save a png with rgba(false). The output is all messed like the attached image above user has shared

**Comment by tgrajewski** [comment]
If you're saving PNGs, then you can try the `colorType()` method on the image:

```javascript
image.colorType(0);  // Grayscale without alpha
image.colorType(2);  // Truecolor without alpha
```

I'm not Jimp contributor, it's just a thing that I've found out in the docs.
