### ISSUE TITLE
Need benchmarks and documentations on memory footprint

### ISSUE THREAD

**Issue by vicary** [jimp-dev/jimp#886]
**Is your feature request related to a problem? Please describe.**
Not a problem related to feature, but instead how should we calculate appropriate resources in the infrastructure based on given a specified input (e.g. maximum file upload size)

**Describe the solution you'd like**
Would like a benchmark on heap size when doing a set of fixed size images, a single time and repeatedly for hundreds and thousands of times. Just some sane numbers to give a general idea.

**Describe alternatives you've considered**
I can do it myself for my specific use case, but concise numbers for library users would be neat.

**Additional context**
Not sure if jimp is ready for comparisons with other packages, but if they are available it would give a far more easy time when new users arrive here from researches.

For example I would love to remove a binary dependency of ImageMagick or GS, so even if there may be a performance hit, I may use this instead.

**Comment by ChristianUlbrich** [comment]
I'd say your specifications are good, you should probably test them for yourself and share here! :) Without having tested _anything whatsoever_, if this is really pure JavaScript you might not get the speed of ImageMagick, but you save yourself a lot of context switches / data marshalling & Co. because the _usual suspects_ are simply nice wrappers around ImageMagick and essentially involve starting a dedicated process for it.

**Comment by hipstersmoothie** [comment]
>  you should probably test them for yourself and share here

I agree!

> if this is really pure JavaScript you might not get the speed of ImageMagick 

You are very right with this one here. `jimp`'s greatest strength and weakness are one in the same:

**It all Javascript!**

---

Upside:

This is really nice because it means that anywhere you can load javascript you can load `jimp`. This is basically the main use case for `jimp`. You want to manipulate images but you dont want to setup your `docker` image to do it with ImageMagick and deal with the hassle or you're in a browser.

---

Downside:

One key part that is also written in javascript is the image encoders and decoders that power the image processing in `jimp`. 

Typically in any piece of software dealing with images you would reach for the real implementation of PNG, JPEG, TIFF, etc. This is usually a library written in `c` or some other low level language. These image libraries are marvels of engineering. They are fast and they work really well. The modern image world is built on them. 

`jimp` does not use any of these things. Those are native deps, definitely not javascript. Instead `jimp` uses the leading `npm` package that re-implements that image type in pure JS. This means reading bits and actually decoding what's in an image. While these libraries work they are not nearly as good as the native equivalent. This is the source of most of the problems with `jimp` come from this fact and are super hard to fix. Those native modules do quite a lot.

The other downside it's easy to write slow javascript, and if you got a lot of pixels it gets slow quick. 

---

That being said there could probably be some work done to improve the speed of some of `jimp` operations. If you find a particularly slow one, don't feel afraid to make a PR.

**Related to Issue:** I think comparing it to a native library is fair but not of a perf basis. There really won't be much of a comparison. The main difference is ease of use.

Happy to accept PRs that have some basic benchmarks though
