### ISSUE TITLE
Alignment 

### ISSUE THREAD

**Issue by hilory16** [jimp-dev/jimp#930]
# Text is supposed to be aligned center horizontally and middle vertically.

# It doesn't print/display the text at all on the image

# No Failure Information

## await image.print(font, 0, 0, { text: name, alignmentX: Jimp.HORIZONTAL_ALIGN_CENTER, alignmentY: Jimp.VERTICAL_ALIGN_MIDDLE }).write(tmpStoragePath);

**Screenshots**

## Context

- Jimp Version:
- Operating System:
- Node version:

**Comment by NickMakesGames** [comment]
Hey Hilory!

I know it's been quite awhile since your original post, but I was experiencing the same issue and found a solution.
Based on this change to the readme: https://github.com/oliver-moran/jimp/pull/703/files
I discovered that you need to specify a max width and max height as additional parameters after your "text" object. It seems that your text will then be centered inside of a box whose top left corner is (0,0), and whose width and height are "max width" and "max height" respectively. 
It's not the most intuitive system, imo, but I hope this helps!

**Comment by walterdl** [comment]
> Hey Hilory!
> 
> I know it's been quite awhile since your original post, but I was experiencing the same issue and found a solution.
> Based on this change to the readme: https://github.com/oliver-moran/jimp/pull/703/files
> I discovered that you need to specify a max width and max height as additional parameters after your "text" object. It seems that your text will then be centered inside of a box whose top left corner is (0,0), and whose width and height are "max width" and "max height" respectively.
> It's not the most intuitive system, imo, but I hope this helps!

Confirmed. It works.

```javascript
const font = await jimp.loadFont(jimp.FONT_SANS_32_BLACK);
const imageHeight = image.getHeight();
const imageWidth = image.getHeight();

image.print(
  font,
  0,
  0,
  {
    text,
    alignmentX: jimp.HORIZONTAL_ALIGN_CENTER,
    alignmentY: jimp.VERTICAL_ALIGN_MIDDLE,
  },
  imageWidth,
  imageHeight,
  (error, image) => {
    // ...
  },
);
```
